version: '3'
services:
  node:
    image: 'node:16.17.0'
    build: .
    command: 'node ./backend/server.js'
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
        MYSQL_DATABASE: 'connectrn'
        MYSQL_USER: 'username'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_HOST: 'mysql'
        MYSQL_PORT: 3306
    depends_on:
      - mysql
  mysql:
    image: 'mysql:8.0'
    restart: always
    environment:
        MYSQL_DATABASE: 'connectrn'
        MYSQL_USER: 'username'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: {} 